country_abbreviations = {
  'AFGHANISTAN': 'AF',
  'Afghanistan': 'AF',
  'ALBANIA': 'AL',
  'Albania': 'AL',
  'ALGERIA': 'DZ',
  'Algeria': 'DZ',
  'AMERICAN SAMOA': 'AS',
  'American Samoa': 'AS',
  'ANDORRA': 'AD',
  'Andorra': 'AD',
  'ANGOLA': 'AO',
  'Angola': 'AO',
  'ANGUILLA': 'AI',
  'Anguilla': 'AI',
  'ANTARCTICA': 'AQ',
  'Antarctica': 'AQ',
  'ANTIGUA AND BARBUDA': 'AG',
  'Antigua And Barbuda': 'AG',
  'ARGENTINA': 'AR',
  'Argentina': 'AR',
  'ARMENIA': 'AM',
  'Armenia': 'AM',
  'ARUBA': 'AW',
  'Aruba': 'AW',
  'AUSTRALIA': 'AU',
  'Australia': 'AU',
  'AUSTRIA': 'AT',
  'Austria': 'AT',
  'AZERBAIJAN': 'AZ',
  'Azerbaijan': 'AZ',
  'BAHAMAS': 'BS',
  'Bahamas': 'BS',
  'BAHRAIN': 'BH',
  'Bahrain': 'BH',
  'BANGLADESH': 'BD',
  'Bangladesh': 'BD',
  'BARBADOS': 'BB',
  'Barbados': 'BB',
  'BELARUS': 'BY',
  'Belarus': 'BY',
  'BELGIUM': 'BE',
  'Belgium': 'BE',
  'BELIZE': 'BZ',
  'Belize': 'BZ',
  'BENIN': 'BJ',
  'Benin': 'BJ',
  'BERMUDA': 'BM',
  'Bermuda': 'BM',
  'BHUTAN': 'BT',
  'Bhutan': 'BT',
  'BOLIVIA': 'BO',
  'Bolivia': 'BO',
  'BOSNIA AND HERZEGOVINA': 'BA',
  'Bosnia And Herzegovina': 'BA',
  'BOTSWANA': 'BW',
  'Botswana': 'BW',
  'BOUVET ISLAND': 'BV',
  'Bouvet Island': 'BV',
  'BRAZIL': 'BR',
  'Brazil': 'BR',
  'BRITISH INDIAN OCEAN TERRITORY': 'IO',
  'British Indian Ocean Territory': 'IO',
  'BRUNEI DARUSSALAM': 'BN',
  'Brunei Darussalam': 'BN',
  'BULGARIA': 'BG',
  'Bulgaria': 'BG',
  'BURKINA FASO': 'BF',
  'Burkina Faso': 'BF',
  'BURUNDI': 'BI',
  'Burundi': 'BI',
  'CAMBODIA': 'KH',
  'Cambodia': 'KH',
  'CAMEROON': 'CM',
  'Cameroon': 'CM',
  'CANADA': 'CA',
  'Canada': 'CA',
  'CAPE VERDE': 'CV',
  'Cape Verde': 'CV',
  'CAYMAN ISLANDS': 'KY',
  'Cayman Islands': 'KY',
  'CENTRAL AFRICAN REPUBLIC': 'CF',
  'Central African Republic': 'CF',
  'CHAD': 'TD',
  'Chad': 'TD',
  'CHILE': 'CL',
  'Chile': 'CL',
  'CHINA': 'CN',
  'China': 'CN',
  'CHRISTMAS ISLAND': 'CX',
  'COCOS (KEELING) ISLANDS': 'CC',
  'COLOMBIA': 'CO',
  'COMOROS': 'KM',
  'CONGO': 'CG',
  'CONGO, THE DEMOCRATIC REPUBLIC OF': 'CD',
  'COOK ISLANDS': 'CK',
  'COSTA RICA': 'CR',
  "CÃ”TE D'IVOIRE": 'CI',
  'CROATIA': 'HR',
  'Croatia': 'HR',
  'CUBA': 'CU',
  'CYPRUS': 'CY',
  'CZECH REPUBLIC': 'CZ',
  'Czech Republic': 'CZ',
  'DENMARK': 'DK',
  'Denmark': 'DK',
  'DJIBOUTI': 'DJ',
  'DOMINICA': 'DM',
  'DOMINICAN REPUBLIC': 'DO',
  'ECUADOR': 'EC',
  'EGYPT': 'EG',
  'EL SALVADOR': 'SV',
  'EQUATORIAL GUINEA': 'GQ',
  'ERITREA': 'ER',
  'ESTONIA': 'EE',
  'ETHIOPIA': 'ET',
  'FALKLAND ISLANDS (MALVINAS)': 'FK',
  'FAROE ISLANDS': 'FO',
  'Faroe Islands': 'FO',
  'FIJI': 'FJ',
  'FINLAND': 'FI',
  'Finland': 'FI',
  'FRANCE': 'FR',
  'France': 'FR',
  'FRENCH GUIANA': 'GF',
  'FRENCH POLYNESIA': 'PF',
  'FRENCH SOUTHERN TERRITORIES': 'TF',
  'GABON': 'GA',
  'GAMBIA': 'GM',
  'GEORGIA': 'GE',
  'GERMANY': 'DE',
  'Germany': 'DE',
  'GHANA': 'GH',
  'GIBRALTAR': 'GI',
  'GREECE': 'GR',
  'Greece': 'GR',
  'GREENLAND': 'GL',
  'GRENADA': 'GD',
  'GUADELOUPE': 'GP',
  'GUAM': 'GU',
  'GUATEMALA': 'GT',
  'GUINEA': 'GW',
  'GUYANA': 'GY',
  'HAITI': 'HT',
  'HEARD ISLAND AND MCDONALD ISLANDS': 'HM',
  'HONDURAS': 'HN',
  'HONG KONG': 'HK',
  'HUNGARY': 'HU',
  'ICELAND': 'IS',
  'Iceland': 'IS',
  'INDIA': 'IN',
  'INDONESIA': 'ID',
  'IRAN, ISLAMIC REPUBLIC OF': 'IR',
  'IRAQ': 'IQ',
  'IRELAND': 'IE',
  'Ireland': 'IE',
  'ISRAEL': 'IL',
  'Israel': 'IL',
  'ITALY': 'IT',
  'Italy': 'IT',
  'JAMAICA': 'JM',
  'JAPAN': 'JP',
  'Japan': 'JP',
  'JORDAN': 'JO',
  'KAZAKHSTAN': 'KZ',
  'Kazakhstan': 'KZ',
  'KENYA': 'KE',
  'KIRIBATI': 'KI',
  "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF": 'KP',
  'KOREA, REPUBLIC OF': 'KR',
  'KUWAIT': 'KW',
  'KYRGYZSTAN': 'KG',
  "LAO PEOPLE'S DEMOCRATIC REPUBLIC": 'LA',
  'LATVIA': 'LV',
  'LEBANON': 'LB',
  'LESOTHO': 'LS',
  'LIBERIA': 'LR',
  'LIBYAN ARAB JAMAHIRIYA': 'LY',
  'LIECHTENSTEIN': 'LI',
  'Liechtenstein': 'LI',
  'LITHUANIA': 'LT',
  'LUXEMBOURG': 'LU',
  'Luxembourg': 'LU',
  'MACAO': 'MO',
  'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF': 'MK',
  'MADAGASCAR': 'MG',
  'MALAWI': 'MW',
  'MALAYSIA': 'MY',
  'MALDIVES': 'MV',
  'MALI': 'ML',
  'MALTA': 'MT',
  'Malta': 'MT',
  'MARSHALL ISLANDS': 'MH',
  'MARTINIQUE': 'MQ',
  'MAURITANIA': 'MR',
  'MAURITIUS': 'MU',
  'MAYOTTE': 'YT',
  'MEXICO': 'MX',
  'MICRONESIA, FEDERATED STATES OF': 'FM',
  'MOLDOVA, REPUBLIC OF': 'MD',
  'MONACO': 'MC',
  'MONGOLIA': 'MN',
  'MONTSERRAT': 'MS',
  'MOROCCO': 'MA',
  'MOZAMBIQUE': 'MZ',
  'MYANMAR': 'MM',
  'NAMIBIA': 'NA',
  'NAURU': 'NR',
  'NEPAL': 'NP',
  'NETHERLANDS': 'NL',
  'Netherlands': 'NL',
  'NETHERLANDS ANTILLES': 'AN',
  'NEW CALEDONIA': 'NC',
  'NEW ZEALAND': 'NZ',
  'NICARAGUA': 'NI',
  'NIGER': 'NE',
  'NIGERIA': 'NG',
  'NIUE': 'NU',
  'NORFOLK ISLAND': 'NF',
  'NORTHERN MARIANA ISLANDS': 'MP',
  'NORWAY': 'NO',
  'Norway': 'NO',
  'OMAN': 'OM',
  'PAKISTAN': 'PK',
  'PALAU': 'PW',
  'PALESTINIAN TERRITORY, OCCUPIED': 'PS',
  'PANAMA': 'PA',
  'PAPUA NEW GUINEA': 'PG',
  'PARAGUAY': 'PY',
  'PERU': 'PE',
  'PHILIPPINES': 'PH',
  'PITCAIRN': 'PN',
  'POLAND': 'PL',
  'Poland': 'PL',
  'PORTUGAL': 'PT',
  'Portugal': 'PT',
  'PUERTO RICO': 'PR',
  'QATAR': 'QA',
  'Qatar': 'QA',
  'RÃ‰UNION': 'RE',
  'ROMANIA': 'RO',
  'Romania': 'RO',
  'RUSSIAN FEDERATION': 'RU',
  'RWANDA': 'RW',
  'SAINT HELENA': 'SH',
  'SAINT KITTS AND NEVIS': 'KN',
  'SAINT LUCIA': 'LC',
  'SAINT PIERRE AND MIQUELON': 'PM',
  'SAINT VINCENT AND THE GRENADINES': 'VC',
  'SAMOA': 'WS',
  'SAN MARINO': 'SM',
  'SAO TOME AND PRINCIPE': 'ST',
  'SAUDI ARABIA': 'SA',
  'Saudi Arabia': 'SA',
  'SENEGAL': 'SN',
  'SERBIA AND MONTENEGRO': 'CS',
  'SEYCHELLES': 'SC',
  'SIERRA LEONE': 'SL',
  'SINGAPORE': 'SG',
  'Singapore': 'SG',
  'SLOVAKIA': 'SK',
  'Slovakia': 'SK',
  'SLOVENIA': 'SI',
  'Slovenia': 'SI',
  'SOLOMON ISLANDS': 'SB',
  'SOMALIA': 'SO',
  'SOUTH AFRICA': 'ZA',
  'SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS': 'GS',
  'SPAIN': 'ES',
  'Spain': 'ES',
  'SRI LANKA': 'LK',
  'SUDAN': 'SD',
  'SURINAME': 'SR',
  'SVALBARD AND JAN MAYEN': 'SJ',
  'SWAZILAND': 'SZ',
  'SWEDEN': 'SE',
  'Sweden': 'SE',
  'SWITZERLAND': 'CH',
  'Switzerland': 'CH',
  'SYRIAN ARAB REPUBLIC': 'SY',
  'TAIWAN, PROVINCE OF CHINA': 'TW',
  'Taiwan': 'TW',
  'TAJIKISTAN': 'TJ',
  'TANZANIA, UNITED REPUBLIC OF': 'TZ',
  'THAILAND': 'TH',
  'Thailand': 'TH',
  'TIMOR': 'TL',
  'TOGO': 'TG',
  'TOKELAU': 'TK',
  'TONGA': 'TO',
  'TRINIDAD AND TOBAGO': 'TT',
  'TUNISIA': 'TN',
  'TURKEY': 'TR',
  'Turkey': 'TR',
  'TURKMENISTAN': 'TM',
  'TURKS AND CAICOS ISLANDS': 'TC',
  'TUVALU': 'TV',
  'UGANDA': 'UG',
  'UKRAINE': 'UA',
  'Ukraine': 'UA',
  'United Arab Emirates': 'AE',
  'UNITED ARAB EMIRATES': 'AE',
  'United Kingdom': 'GB',
  'United States': 'US',
  'USA': 'US',
  'Usa': 'US',
  'UNITED STATES MINOR OUTLYING ISLANDS': 'UM',
  'URUGUAY': 'UY',
  'UZBEKISTAN': 'UZ',
  'VANUATU': 'VU',
  'VIET NAM': 'VN',
  'VIRGIN ISLANDS, BRITISH': 'VG',
  'VIRGIN ISLANDS, U.S.': 'VI',
  'WALLIS AND FUTUNA': 'WF',
  'WESTERN SAHARA': 'EH',
  'YEMEN': 'YE',
  'ZIMBABWE': 'ZW',
}