
us_states = [
    'Alabama', 'ALABAMA', 'Alaska', 'ALASKA', 'Arizona', 'ARIZONA', 'Arkansas', 'ARKANSAS',
    'California', 'CALIFORNIA', 'Colorado', 'COLORADO', 'Connecticut', 'CONNECTICUT', 'Delaware', 'DELAWARE',
    'Florida', 'FLORIDA', 'Georgia', 'GEORGIA', 'Hawaii', 'HAWAII', 'Idaho', 'IDAHO', 'Illinois', 'ILLINOIS',
    'Indiana', 'INDIANA', 'Iowa', 'IOWA', 'Kansas', 'KANSAS', 'Kentucky', 'KENTUCKY', 'Louisiana', 'LOUISIANA',
    'Maine', 'MAINE', 'Maryland', 'MARYLAND', 'Massachusetts', 'MASSACHUSETTS', 'Michigan', 'MICHIGAN',
    'Minnesota', 'MINNESOTA', 'Mississippi', 'MISSISSIPPI', 'Missouri', 'MISSOURI', 'Montana', 'MONTANA',
    'Nebraska', 'NEBRASKA', 'Nevada', 'NEVADA', 'New Hampshire', 'NEW HAMPSHIRE', 'New Jersey', 'NEW JERSEY',
    'New Mexico', 'NEW MEXICO', 'New York', 'NEW YORK', 'North Carolina', 'NORTH CAROLINA', 'North Dakota', 'NORTH DAKOTA',
    'Ohio', 'OHIO', 'Oklahoma', 'OKLAHOMA', 'Oregon', 'OREGON', 'Pennsylvania', 'PENNSYLVANIA', 'Rhode Island', 'RHODE ISLAND',
    'South Carolina', 'SOUTH CAROLINA', 'South Dakota', 'SOUTH DAKOTA', 'Tennessee', 'TENNESSEE', 'Texas', 'TEXAS',
    'Utah', 'UTAH', 'Vermont', 'VERMONT', 'Virginia', 'VIRGINIA', 'Washington', 'WASHINGTON', 'West Virginia', 'WEST VIRGINIA',
    'Wisconsin', 'WISCONSIN', 'Wyoming', 'WYOMING', 'District of Columbia', 'DISTRICT OF COLUMBIA', 'American Samoa', 'AMERICAN SAMOA',
    'Guam', 'GUAM', 'Northern Mariana Islands', 'NORTHERN MARIANA ISLANDS', 'Puerto Rico', 'PUERTO RICO',
    'United States Minor Outlying Islands', 'UNITED STATES MINOR OUTLYING ISLANDS', 'U.S. Virgin Islands', 'U.S. VIRGIN ISLANDS',
    "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DC", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD",
    "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD",
    "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"
]


us_state_to_abbrev = {
    "Alabama": "AL",
    "ALABAMA": "AL",
    "Alaska": "AK",
    "ALASKA": "AK",
    "Arizona": "AZ",
    "ARIZONA": "AZ",
    "Arkansas": "AR",
    "ARKANSAS": "AR",
    "California": "CA",
    "CALIFORNIA": "CA",
    "Colorado": "CO",
    "COLORADO": "CO",
    "Connecticut": "CT",
    "CONNECTICUT": "CT",
    "Delaware": "DE",
    "DELAWARE": "DE",
    "Florida": "FL",
    "FLORIDA": "FL",
    "Georgia": "GA",
    "GEORGIA": "GA",
    "Hawaii": "HI",
    "HAWAII": "HI",
    "Idaho": "ID",
    "IDAHO": "ID",
    "Illinois": "IL",
    "ILLINOIS": "IL",
    "Indiana": "IN",
    "INDIANA": "IN",
    "Iowa": "IA",
    "IOWA": "IA",
    "Kansas": "KS",
    "KANSAS": "KS",
    "Kentucky": "KY",
    "KENTUCKY": "KY",
    "Louisiana": "LA",
    "LOUISIANA": "LA",
    "Maine": "ME",
    "MAINE": "ME",
    "Maryland": "MD",
    "MARYLAND": "MD",
    "Massachusetts": "MA",
    "MASSACHUSETTS": "MA",
    "Michigan": "MI",
    "MICHIGAN": "MI",
    "Minnesota": "MN",
    "MINNESOTA": "MN",
    "Mississippi": "MS",
    "MISSISSIPPI": "MS",
    "Missouri": "MO",
    "MISSOURI": "MO",
    "Montana": "MT",
    "MONTANA": "MT",
    "Nebraska": "NE",
    "NEBRASKA": "NE",
    "Nevada": "NV",
    "NEVADA": "NV",
    "New Hampshire": "NH",
    "NEW HAMPSHIRE": "NH",
    "New Jersey": "NJ",
    "NEW JERSEY": "NJ",
    "New Mexico": "NM",
    "NEW MEXICO": "NM",
    "New York": "NY",
    "NEW YORK": "NY",
    "North Carolina": "NC",
    "NORTH CAROLINA": "NC",
    "North Dakota": "ND",
    "NORTH DAKOTA": "ND",
    "Ohio": "OH",
    "OHIO": "OH",
    "Oklahoma": "OK",
    "OKLAHOMA": "OK",
    "Oregon": "OR",
    "OREGON": "OR",
    "Pennsylvania": "PA",
    "PENNSYLVANIA": "PA",
    "Rhode Island": "RI",
    "RHODE ISLAND": "RI",
    "South Carolina": "SC",
    "SOUTH CAROLINA": "SC",
    "South Dakota": "SD",
    "SOUTH DAKOTA": "SD",
    "Tennessee": "TN",
    "TENNESSEE": "TN",
    "Texas": "TX",
    "TEXAS": "TX",
    "Utah": "UT",
    "UTAH": "UT",
    "Vermont": "VT",
    "VERMONT": "VT",
    "Virginia": "VA",
    "VIRGINIA": "VA",
    "Washington": "WA",
    "WASHINGTON": "WA",
    "West Virginia": "WV",
    "WEST VIRGINIA": "WV",
    "Wisconsin": "WI",
    "WISCONSIN": "WI",
    "Wyoming": "WY",
    "WYOMING": "WY",
    "District of Columbia": "DC",
    "DISTRICT OF COLUMBIA": "DC",
    "American Samoa": "AS",
    "AMERICAN SAMOA": "AS",
    "Guam": "GU",
    "GUAM": "GU",
    "Northern Mariana Islands": "MP",
    "NORTHERN MARIANA ISLANDS": "MP",
    "Puerto Rico": "PR",
    "PUERTO RICO": "PR",
    "United States Minor Outlying Islands": "UM",
    "UNITED STATES MINOR OUTLYING ISLANDS": "UM",
    "U.S. Virgin Islands": "VI",
    "U.S. VIRGIN ISLANDS": "VI",
}